name: get_ongkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_search: 5.0.2
  dio: 4.0.6
  http: 0.13.4
  intl: 0.17.0
  flutter: 
    sdk: flutter
  fluttertoast: ^8.0.9
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  shared_preferences: ^2.0.15
  faker: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
       

